### ISSUE TITLE
-Xmx1024m

### ISSUE THREAD

**Issue by kwanpham** [tyrion9/spring-boot-startup-script#1]
Bác cho em hỏi đoạn JAVA_OPT=-Xmx1024m để làm gì không , thanks bác

**Comment by tyrion9** [comment]
Mình tuỳ chỉnh tham số cho Java bạn ơi (java option). Ở đây mình đặt giới hạn 1g ram đó

**Comment by kwanpham** [comment]
Thanks bác , đoạc code của bác thiếu cái status , nên em viết bổ sung trong code của em , bác check thử nhé

`#!/bin/bash -

# Created by https://github.com/kwanpham

#=-= START OF CUSTOM SERVICE CONFIGURATION =-#
# Where micro service war/jar file sits?
MS_HOME=/home/test # <--- EDIT THIS LINE

# Actual file name of Micro Service (jar or war), 
# ms-service.war or something-0.0.1-SNAPSHOT.jar, etc.
MS_JAR=spring-boot-admin-demo-0.0.1-SNAPSHOT.jar # <--- EDIT THIS LINE
# ^^^ that should relative to MS_HOME directory.

MS_SERVICE=${MS_JAR%.*}

MS_LOG=/tmp/log/${MS_SERVICE}.log

# Which username we should run as.
RUNASUSER=root; # <-- EDIT THIS LINE, 
# if port number for spring boot is < 1024 it needs root perm.

#JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64; # <-- EDIT THIS, Where is your JDK/JRE?
#PATH=${JAVA_HOME}/bin:${PATH};
SHUTDOWN_WAIT=20; # before issuing kill -9 on process.

#export PATH JAVA_HOME


# These options are used when micro service is starting 
# Add whatever you want/need here... overrides application*.yml.
OPTIONS=" -Xms256m ";
#=-= END OF CUSTOM CONFIGURATION =-=#

# Try to get PID of spring jar/war
MS_PID=`ps fax|grep java|grep "${MS_JAR}"|awk '{print $1}'`
export MS_PID;

# Function: run_as
run_as() {
    local iam iwant;

    iam=$(id -nu);
    iwant="$1";
    shift;

    if [ "${iam}" = "${iwant}" ]; then {
    eval $*;
    }
    else {
    /bin/su -p -s /bin/sh ${iwant} $*;
    } fi;
}

# Function: start
start() {
 if [ ! -f  "$MS_JAR" ];
 then
	echo "ERROR: ${MS_JAR} file not found";
	exit 1
 fi;

  pid=${MS_PID}
  if [ -n "${pid}" ]; then {
    echo "Service : ${MS_JAR} is already running (pid: ${pid})";
  }
  else {
    # Start screener ms
    echo "Starting micro service ${MS_SERVICE}";
    cd $MS_HOME
    nohup java -jar ${OPTIONS} ./${MS_JAR} > ${MS_LOG} 2>&1 &
	sleep 0.75
    echo "${MS_SERVICE} is running at pid: "$! ;
   
  } fi;
  # return 0;
}

# Function: stop
stop() {
  pid=${MS_PID}
  if [ -n "${pid}" ]; then {

#    run_as ${RUNASUSER} kill -TERM $pid
	kill -TERM $pid
    echo -ne "Stopping micro service module ${MS_SERVICE} ";

    kwait=${SHUTDOWN_WAIT};

    count=0;
    while kill -0 ${pid} 2>/dev/null && [ ${count} -le ${kwait} ]; do {
      printf ".";
      sleep 1;
      (( count++ ));
    } done;

    echo;

    if [ ${count} -gt ${kwait} ]; then {
      printf "Process is still running after %d seconds, killing process" \
    ${SHUTDOWN_WAIT};
      kill ${pid};
      sleep 3;

      # if it's still running use kill -9
      #
      if kill -0 ${pid} 2>/dev/null; then {
        echo "Process is still running, using kill -9";
        kill -9 ${pid}
        sleep 3;
      } fi;
    } fi;

    if kill -0 ${pid} 2>/dev/null; then {
      echo "Error: process is still running, I give up";
    } 
    else {
      # success, delete PID file, if you have used it with spring boot
      rm -f ${SPRING_BOOT_APP_PID};
    } fi;
  } 
  else {
      echo "Service : ${MS_SERVICE} is not running";
  } fi;

  #return 0;
}

# Function: status
status() {
pid=$MS_PID
    if [ "${pid}" ]; then {
	port=`ss -l -p -n | grep "pid=${pid}," | awk '{print $5}'`

      	echo "Service : ${MS_SERVICE} is running with pid: ${pid} and port ${port}";
    }
    else {
      echo "Service : ${MS_SERVICE} is not running";
    } fi;
}
# Main Code

case $1 in
  start)
    start;
    ;;
  stop)
    stop;
    ;;
  restart)
    stop;
    sleep 1;
    start;
    ;;
  status)
    status;
    ;;
esac

exit 0;`
